backend:
  name: github
  repo: hellcat1561/hellcat.github.io
  branch: main
  base_url: https://hellcat-cms-oauth.fly.dev
  auth_endpoint: auth
  token_endpoint: token

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "journal"
    label: "Journal"
    folder: "journal"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "artwork"
    label: "Artwork"
    folder: "artwork"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
